apiVersion: apps/v1
kind: Deployment
metadata: # Deployment blue print 
  name: nginx-deployment
  labels:
    app: nginx
spec: # Specification for deployment 
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: # POD Blue Print 
    metadata:
      labels:
        app: nginx
    spec: # Spec for pods
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080

